services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ~/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    ports:
      - "9092:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    depends_on:
      - prometheus
      - langfuse-web
    environment:
      LANGFUSE_AUTH: ${LANGFUSE_AUTH}
    volumes:
      - ~/otel/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"

volumes:
  prom_data: